// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

module regblock (
        input wire clk,
        input wire rst,

        input wire avalon_read,
        input wire avalon_write,
        output logic avalon_waitrequest,
        input wire [1:0] avalon_address,
        input wire [31:0] avalon_writedata,
        input wire [3:0] avalon_byteenable,
        output logic avalon_readdatavalid,
        output logic avalon_writeresponsevalid,
        output logic [31:0] avalon_readdata,
        output logic [1:0] avalon_response,

        output logic [31:0] hwif_out_r_w_f
    );

    //--------------------------------------------------------------------------
    // CPU Bus interface logic
    //--------------------------------------------------------------------------
    logic cpuif_req;
    logic cpuif_req_is_wr;
    logic [3:0] cpuif_addr;
    logic [31:0] cpuif_wr_data;
    logic [31:0] cpuif_wr_biten;
    logic cpuif_req_stall_wr;
    logic cpuif_req_stall_rd;

    logic cpuif_rd_ack;
    logic cpuif_rd_err;
    logic [31:0] cpuif_rd_data;

    logic cpuif_wr_ack;
    logic cpuif_wr_err;



    // Request
    always_comb begin
        cpuif_req = avalon_read | avalon_write;
        cpuif_req_is_wr = avalon_write;
        cpuif_addr = {avalon_address, 2'b0};
        cpuif_wr_data = avalon_writedata;
        for(int i=0; i<4; i++) begin
            cpuif_wr_biten[i*8 +: 8] = {8{avalon_byteenable[i]}};
        end
        avalon_waitrequest = (cpuif_req_stall_rd & avalon_read) | (cpuif_req_stall_wr & avalon_write);
    end

    // Response
    always_comb begin
        avalon_readdatavalid = cpuif_rd_ack;
        avalon_writeresponsevalid = cpuif_wr_ack;
        avalon_readdata = cpuif_rd_data;
        if(cpuif_rd_err || cpuif_wr_err) begin
            // SLVERR
            avalon_response = 2'b10;
        end else begin
            // OK
            avalon_response = 2'b00;
        end
    end

    logic cpuif_req_masked;

    // Read & write latencies are balanced. Stalls not required
    assign cpuif_req_stall_rd = '0;
    assign cpuif_req_stall_wr = '0;
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

    //--------------------------------------------------------------------------
    // Address Decode
    //--------------------------------------------------------------------------
    logic [0:0] decoded_reg_strb_r_rw;
    logic [0:0] decoded_reg_strb_r_r;
    logic [0:0] decoded_reg_strb_r_w;
    logic decoded_err;

    logic decoded_req;
    logic decoded_req_is_wr;
    /* verilator lint_off UNUSEDSIGNAL */
    logic [31:0] decoded_wr_data;
    logic [31:0] decoded_wr_biten;
    /* verilator lint_on UNUSEDSIGNAL */

    always @(*) begin
        /* verilator lint_off UNUSEDSIGNAL */
        integer next_cpuif_addr;
        /* verilator lint_on UNUSEDSIGNAL */
        logic is_valid_addr;
        logic is_invalid_rw;
        is_valid_addr = '0;
        is_invalid_rw = '0;
        decoded_reg_strb_r_rw = cpuif_req_masked & (cpuif_addr == 4'h0);
        is_valid_addr |= cpuif_req_masked & (cpuif_addr == 4'h0);
        is_invalid_rw |= '0;
        decoded_reg_strb_r_r = cpuif_req_masked & (cpuif_addr == 4'h4) & !cpuif_req_is_wr;
        is_valid_addr |= cpuif_req_masked & (cpuif_addr == 4'h4);
        is_invalid_rw |= cpuif_req_masked & (cpuif_addr == 4'h4) & cpuif_req_is_wr;
        decoded_reg_strb_r_w = cpuif_req_masked & (cpuif_addr == 4'h8) & cpuif_req_is_wr;
        is_valid_addr |= cpuif_req_masked & (cpuif_addr == 4'h8);
        is_invalid_rw |= cpuif_req_masked & (cpuif_addr == 4'h8) & !cpuif_req_is_wr;
        decoded_err = (~is_valid_addr | is_invalid_rw) & decoded_req;
    end

    // Pass down signals to next stage
    assign decoded_req = cpuif_req_masked;
    assign decoded_req_is_wr = cpuif_req_is_wr;
    assign decoded_wr_data = cpuif_wr_data;
    assign decoded_wr_biten = cpuif_wr_biten;


    //--------------------------------------------------------------------------
    // Field storage declarations
    //--------------------------------------------------------------------------

    // Field: regblock.r_rw.f
    logic [31:0] field_storage_r_rw_f_value;
    logic [31:0] field_combo_r_rw_f_next;
    logic field_combo_r_rw_f_load_next;
    // Field: regblock.r_w.f
    logic [31:0] field_storage_r_w_f_value;
    logic [31:0] field_combo_r_w_f_next;
    logic field_combo_r_w_f_load_next;
    //--------------------------------------------------------------------------
    // Field logic
    //--------------------------------------------------------------------------
    // always_comb begin
    always @(*) begin
        logic [31:0] next_c;
        logic load_next_c;
        next_c = field_storage_r_rw_f_value;
        load_next_c = '0;
        if(decoded_reg_strb_r_rw && decoded_req_is_wr) begin // SW write
            next_c = (field_storage_r_rw_f_value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo_r_rw_f_next = next_c;
        field_combo_r_rw_f_load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage_r_rw_f_value <= 32'h28;
        end else if(field_combo_r_rw_f_load_next) begin
            field_storage_r_rw_f_value <= field_combo_r_rw_f_next;
        end
    end
    // always_comb begin
    always @(*) begin
        logic [31:0] next_c;
        logic load_next_c;
        next_c = field_storage_r_w_f_value;
        load_next_c = '0;
        if(decoded_reg_strb_r_w && decoded_req_is_wr) begin // SW write
            next_c = (field_storage_r_w_f_value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo_r_w_f_next = next_c;
        field_combo_r_w_f_load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage_r_w_f_value <= 32'h64;
        end else if(field_combo_r_w_f_load_next) begin
            field_storage_r_w_f_value <= field_combo_r_w_f_next;
        end
    end
    assign hwif_out_r_w_f = field_storage_r_w_f_value;

    //--------------------------------------------------------------------------
    // Write response
    //--------------------------------------------------------------------------
    assign cpuif_wr_ack = decoded_req & decoded_req_is_wr;
    // Writes are always granted with no error response
    assign cpuif_wr_err = decoded_err;

//--------------------------------------------------------------------------
// Readback
//--------------------------------------------------------------------------
    logic readback_external_rd_ack;
    assign readback_external_rd_ack = 0;

    logic readback_err;
    logic readback_done;
    logic [31:0] readback_data;

    // Assign readback values to a flattened array
    logic [31:0] readback_array[2];
    assign readback_array[0][31:0] = (decoded_reg_strb_r_rw && !decoded_req_is_wr) ? field_storage_r_rw_f_value : '0;
    assign readback_array[1][31:0] = (decoded_reg_strb_r_r && !decoded_req_is_wr) ? 32'h50 : '0;

    // Reduce the array
    // always_comb begin
    always @(*) begin
        logic [31:0] readback_data_var;
        readback_done = decoded_req & ~decoded_req_is_wr;
        readback_err = decoded_err;
        readback_data_var = '0;
        for(int i=0; i<2; i++) readback_data_var |= readback_array[i];
        readback_data = readback_data_var;
    end

    assign cpuif_rd_ack = readback_done;
    assign cpuif_rd_data = readback_data;
    assign cpuif_rd_err = readback_err;
endmodule
